/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangeDefaultPasswordDialog.java
 *
 * Created on Oct 15, 2011, 9:59:13 AM
 */
package ised.gui.dialog;

import ised.model.Adviser;
import ised.model.SchoolYear;
import ised.model.Class;
import ised.model.Employee;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ised.model.UserAccount;
import ised.service.implementation.AdviserServiceImpl;
import ised.service.implementation.ClassServiceImpl;
import ised.service.implementation.UserAccountServiceImpl;
import ised.service.interfaces.AdviserService;
import ised.service.interfaces.ClassService;
import ised.service.interfaces.UserAccountService;
import ised.tools.ComponentFormatter;
import ised.tools.ExceptionHandler;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABDUL
 */
public class AdviserDialog extends javax.swing.JDialog {

    private javax.swing.JFrame parentFrame;
    private SchoolYear currentSchoolYear;
    private DefaultTableModel classTableModel;
    private AdviserService adviserService;
    private ClassService classService;
    private List<Class> classList;
    private Employee faculty;
    private Adviser advisee;
    private boolean isAdd;
    private String title;
    public boolean success = false;

    /** Creates new form ChangeDefaultPasswordDialog */
    public AdviserDialog(javax.swing.JFrame parentFrame, boolean modal, Employee faculty, Adviser advisee, SchoolYear schoolYear) throws ExceptionHandler {
        super(parentFrame, modal);
        initComponents();
        this.parentFrame = parentFrame;
        this.faculty = faculty;
        this.advisee = advisee;
        this.setLocationRelativeTo(parentFrame);
        currentSchoolYear = schoolYear;
        classTableModel = (DefaultTableModel) classTable.getModel();
        adviserService = new AdviserServiceImpl();
        classService = new ClassServiceImpl();
        displayAdviserList();
        isAdd = true;
        title = "Add Advisee";
        selectAdvisee();
    }

    private void displayAdviserList() throws ExceptionHandler {
        classList = classService.getClassList(currentSchoolYear.getSchoolYearID(), "Active");
        ComponentFormatter.clearTable(classTableModel);
        for (Class section : classList) {
            classTableModel.addRow(new Object[]{getYearLevel(section.getYearLevel()) + " - " + section.getSection().getSectionName(),
                        getAdviser(section) == null ? "No adviser assigned" : getAdviser(section).getEmployee().getFullName()});
        }
    }

    private void selectAdvisee() {
        if (advisee != null) {
            int classIndex = -1;
            title = "Edit Advisee";
            isAdd = false;
            for (Class section : classList) {
                if (advisee.getSection().getClassID() == section.getClassID()) {
                    classIndex = classList.indexOf(section);
                }
            }
            classTable.setRowSelectionInterval(classIndex, classIndex);
        }
    }

    private String getYearLevel(int yearLevel) {
        if (yearLevel == 1) {
            return "I";
        } else if (yearLevel == 2) {
            return "II";
        } else if (yearLevel == 3) {
            return "III";
        } else if (yearLevel == 4) {
            return "IV";
        }
        return "";
    }

    private Adviser getAdviser(Class section) throws ExceptionHandler {
        return adviserService.getAdviser(section.getClassID());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        saveButton.setBackground(new java.awt.Color(0, 204, 51));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/accept.png"))); // NOI18N
        saveButton.setText("Add");
        saveButton.setOpaque(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(0, 204, 51));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/cross.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setOpaque(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        classTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Yr. Level and Section", "Adviser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classTable);
        classTable.getColumnModel().getColumn(0).setMinWidth(120);
        classTable.getColumnModel().getColumn(0).setPreferredWidth(120);
        classTable.getColumnModel().getColumn(0).setMaxWidth(120);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            int index = classTable.getSelectedRow();
            if (index >= 0) {
                Class section = classList.get(index);

                if (isAdd) {
                    adviserService.addAdvisee(section.getClassID(), faculty.getEmployeeID());
                } else {
                    adviserService.editAdvisee(section.getClassID(), advisee.getAdviserID());
                }
                success = true;
                JOptionPane.showMessageDialog(parentFrame, "Employee has successfully assigned to the section", title, JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(parentFrame, "No section selected", "Add advisee", JOptionPane.WARNING_MESSAGE);
            }
        } catch (ExceptionHandler ex) {
        }
}//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable classTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
