/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateUserAccountDialog.java
 *
 * Created on Sep 28, 2011, 10:58:58 PM
 */
package ised.gui.dialog;

import ised.model.Employee;
import ised.model.UserAccount;
import ised.service.implementation.UserAccountServiceImpl;
import ised.service.interfaces.UserAccountService;
import ised.tools.ExceptionHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodel
 */
public class CreateUserAccountDialog extends javax.swing.JDialog {

    private Employee employee;
    private UserAccountService userAccountService;
    private javax.swing.JFrame parentFrame;
    public boolean success;

    /** Creates new form CreateUserAccountDialog */
    public CreateUserAccountDialog(javax.swing.JFrame parentFrame, boolean modal) throws ExceptionHandler {
        super(parentFrame, modal);
        initComponents();
        success = false;
        this.parentFrame = parentFrame;
        this.setLocationRelativeTo(parentFrame);
        userAccountService = new UserAccountServiceImpl();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox();
        employeeTextField = new javax.swing.JTextField();
        viewEmployeeList = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Create User Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Employee");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        userNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("User Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        userTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Registrar", "Enrolling Officer", "Principal", "Teacher", "Academic Consultant", "Administrator" }));
        jPanel1.add(userTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 174, -1));

        employeeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        employeeTextField.setEnabled(false);
        jPanel1.add(employeeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, -1));

        viewEmployeeList.setText("...");
        viewEmployeeList.setOpaque(false);
        viewEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeListActionPerformed(evt);
            }
        });
        jPanel1.add(viewEmployeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 40, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/disk.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setOpaque(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setOpaque(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (employee == null) {
            JOptionPane.showMessageDialog(this, "Please select an employee",
                    "Create User Account", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (userNameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username is empty.",
                    "Create User Account", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String userName = userNameTextField.getText();
            String userType = userTypeComboBox.getSelectedItem().toString();
            if (userAccountService.checkUserName(userName)) {
                if (userAccountService.checkUserAccount(employee.getEmployeeID(), userType)) {
                    UserAccount user = new UserAccount(userName, userType, employee);
                    userAccountService.addUserAccount(user);
                    success = true;
                    JOptionPane.showMessageDialog(this, "User account has successfully created",
                            "Create User Account", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Employee has already existing account with the same user type.",
                        "Create User Account", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username is already in use. Please use another username.",
                        "Create User Account", JOptionPane.WARNING_MESSAGE);
            }
        } catch (ExceptionHandler ex) {
            Logger.getLogger(CreateUserAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void viewEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeListActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeListDialog employeeList = new EmployeeListDialog(parentFrame, true);
            employeeList.setVisible(true);
            employee = employeeList.getSelectedEmployee();
            if (employee != null) {
                employeeTextField.setText(employee.getFullName());
                userNameTextField.setText(generateUserName(employee));
            }
        } catch (ExceptionHandler ex) {
            Logger.getLogger(CreateUserAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewEmployeeListActionPerformed

    private String generateUserName(Employee employee) {
        return (employee.getFirstName().charAt(0) + employee.getLastName().trim()).toLowerCase();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField employeeTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JComboBox userTypeComboBox;
    private javax.swing.JButton viewEmployeeList;
    // End of variables declaration//GEN-END:variables
}
