/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateUserAccountDialog.java
 *
 * Created on Sep 28, 2011, 10:58:58 PM
 */
package ised.gui.dialog;

import ised.model.UserAccount;
import ised.service.implementation.UserAccountServiceImpl;
import ised.service.interfaces.UserAccountService;
import ised.tools.ExceptionHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodel
 */
public class EditUserAccountDialog extends javax.swing.JDialog {

    private UserAccount user;
    private UserAccountService userAccountService;
    private javax.swing.JFrame parentFrame;
    public boolean success;

    /** Creates new form CreateUserAccountDialog */
    public EditUserAccountDialog(javax.swing.JFrame parentFrame, boolean modal, UserAccount user) throws ExceptionHandler {
        super(parentFrame, modal);
        initComponents();
        success = false;
        this.parentFrame = parentFrame;
        this.setLocationRelativeTo(parentFrame);
        this.user = user;
        userAccountService = new UserAccountServiceImpl();
        displayUserInfo();
    }

    private void displayUserInfo() {
        employeeTextField.setText(user.getEmployee().getFullName());
        userNameTextField.setText(user.getUserName());
        userTypeComboBox.setSelectedItem(user.getUserType());
        if (user.getStatus().equalsIgnoreCase("Active")) {
            activeCheckBox.setSelected(true);
        } else {
            inactiveCheckBox.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusButtonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox();
        employeeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        activeCheckBox = new javax.swing.JCheckBox();
        inactiveCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Edit User Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Employee");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        userNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("User Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        userTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Registrar", "Enrolling Officer", "Principal", "Teacher", "Academic Consultant", "Administrator" }));
        jPanel1.add(userTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 174, -1));

        employeeTextField.setFont(new java.awt.Font("Tahoma", 0, 12));
        employeeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        employeeTextField.setEnabled(false);
        jPanel1.add(employeeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 220, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        statusButtonGroup.add(activeCheckBox);
        activeCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        activeCheckBox.setText("Active");
        activeCheckBox.setOpaque(false);
        jPanel1.add(activeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        statusButtonGroup.add(inactiveCheckBox);
        inactiveCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        inactiveCheckBox.setText("Inactive");
        inactiveCheckBox.setOpaque(false);
        jPanel1.add(inactiveCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/reset_password.png"))); // NOI18N
        jButton1.setText("Reset Password");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 30));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/disk.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setOpaque(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setOpaque(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(99, 99, 99))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (userNameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username is invalid.",
                    "Edit User Account", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String userName = userNameTextField.getText();
            String userType = userTypeComboBox.getSelectedItem().toString();
            String status = activeCheckBox.isSelected() ? "Active" : "Inactive";
            if (userAccountService.checkUserName(userName) || user.getUserName().equalsIgnoreCase(userName)) {
                user.setUserName(userName);
                user.setStatus(status);
                user.setUserType(userType);
                userAccountService.editUserAccount(user);
                success = true;
                JOptionPane.showMessageDialog(this, "User account has successfully edited",
                        "Edit User Account", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Username is already in use. Please use another username.",
                        "Edit User Account", JOptionPane.WARNING_MESSAGE);
            }
        } catch (ExceptionHandler ex) {
            Logger.getLogger(EditUserAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset the password?", "Reset Password", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                userAccountService.resetPassword(user.getUserID());
                user.setPassword("123456");
                 //JOptionPane.showMessageDialog(this, "Password is successfully reset to default password",
                  //      "Edit User Account", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (ExceptionHandler ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField employeeTextField;
    private javax.swing.JCheckBox inactiveCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup statusButtonGroup;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JComboBox userTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
