/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addCurriculum.java
 *
 * Created on Oct 4, 2011, 12:07:43 AM
 */
package ised.gui.dialog;

import ised.model.SummerStudent;
import ised.service.implementation.SummerStudentServiceImpl;
import ised.service.interfaces.SummerStudentService;
import ised.tools.ExceptionHandler;

/**
 *
 * @author Rodel
 */
public class EnterGradeDialog extends javax.swing.JDialog {

    private SummerStudentService summerStudentService;
    private javax.swing.JFrame parentFrame;
    private SummerStudent summerStudent;
    public boolean success = false;

    public EnterGradeDialog(javax.swing.JFrame parentFrame, boolean modal, SummerStudent summerStudent) {
        super(parentFrame, true);
        initComponents();
        this.parentFrame = parentFrame;
        this.setLocationRelativeTo(parentFrame);
        summerStudentService = new SummerStudentServiceImpl();
        this.summerStudent = summerStudent;
        displayInfo();
    }

    private void displayInfo() {
        name.setText(summerStudent.getStudentSubject().getEnrollment().getAdmission().getStudent().getFullName());
        if (summerStudent.getCompleteGrade() == 0) {
            gradeComboBox.setSelectedItem(summerStudent.getCompleteGrade());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        subjectCodeLabel = new javax.swing.JLabel();
        unitsLabel = new javax.swing.JLabel();
        gradeComboBox = new javax.swing.JComboBox();
        name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subjectCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        subjectCodeLabel.setText("Name:");

        unitsLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        unitsLabel.setText("Grade:");

        gradeComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gradeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "5.0" }));

        name.setFont(new java.awt.Font("Tahoma", 0, 12));
        name.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectCodeLabel)
                    .addComponent(unitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(gradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitsLabel)
                    .addComponent(gradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/disk.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 88, 27));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/cancel.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 97, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            double grade = Double.parseDouble(gradeComboBox.getSelectedItem().toString());
            summerStudentService.enterGrade(summerStudent.getStudentSubject().getStudentSubjectID(), grade);
            success = true;
            this.setVisible(false);
        } catch (ExceptionHandler ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox gradeComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel subjectCodeLabel;
    private javax.swing.JLabel unitsLabel;
    // End of variables declaration//GEN-END:variables
}
