/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchoolYearDialog.java
 *
 * Created on 11 9, 11, 11:13:50 PM
 */
package ised.gui.dialog;

import ised.model.SchoolYear;
import ised.tools.ComponentFormatter;
import ised.service.implementation.SchoolYearServiceImpl;
import ised.service.interfaces.SchoolYearService;
import ised.tools.ExceptionHandler;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABDUL
 */
public class SchoolYearDialog extends javax.swing.JDialog {

    private SchoolYear selectedSchoolYear;
    private SchoolYearService schoolYearService;
    private boolean isAdd;
    private javax.swing.JFrame parentFrame;
    public boolean success = false;

    /** Creates new form SchoolYearDialog */
    public SchoolYearDialog(javax.swing.JFrame parentFrame, boolean modal, SchoolYear schoolYear, boolean isAdd) {
        super(parentFrame, modal);
        initComponents();
        this.parentFrame = parentFrame;
        this.setLocationRelativeTo(parentFrame);
        this.selectedSchoolYear = schoolYear;
        this.isAdd = isAdd;
        schoolYearService = new SchoolYearServiceImpl();
        setComboBox();
        displaySchoolYearInfo();
    }

    private void setComboBox() {
        ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthEnrollmentStartComboBox, dayEnrollmentStartComboBox);
        ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthEnrollmentEndComboBox, dayEnrollmentEndComboBox);
        ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthStartOfClassesComboBox, dayStartOfClassesComboBox);
    }

    private void displaySchoolYearInfo() {
        if (!isAdd) {
            schoolYearTextField.setText(selectedSchoolYear.toString());
            statusComboBox.setSelectedItem(selectedSchoolYear.getSchoolYearStatus());
            if (selectedSchoolYear.getSchoolYearStatus().equalsIgnoreCase("Inactive")) {
                statusComboBox.setEnabled(true);
                enrollmentStartCheckBox.setEnabled(false);
                enrollmentEndCheckBox.setEnabled(false);
                startOfClassesCheckBox.setEnabled(false);
                return;
            }
            if (selectedSchoolYear.getEnrollmentBegin() != null) {
                enrollmentStartCheckBox.setSelected(true);
                updateEnrollmentStartComboBox(true);
                ComponentFormatter.formatDateNoToWord(selectedSchoolYear.getEnrollmentBegin(), monthEnrollmentStartComboBox, dayEnrollmentStartComboBox);
            }
            if (selectedSchoolYear.getEnrollmentEnd() != null) {
                enrollmentEndCheckBox.setSelected(true);
                updateEnrollmentEndComboBox(true);
                ComponentFormatter.formatDateNoToWord(selectedSchoolYear.getEnrollmentEnd(), monthEnrollmentEndComboBox, dayEnrollmentEndComboBox);
            }
            if (selectedSchoolYear.getStartOfClasses() != null) {
                startOfClassesCheckBox.setSelected(true);
                updateStartOfClassesComboBox(true);
                ComponentFormatter.formatDateNoToWord(selectedSchoolYear.getStartOfClasses(), monthStartOfClassesComboBox, dayStartOfClassesComboBox);
            }
        } else {
            schoolYearTextField.setText(selectedSchoolYear.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        schoolYearTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox();
        dayEnrollmentStartComboBox = new javax.swing.JComboBox();
        monthEnrollmentEndComboBox = new javax.swing.JComboBox();
        dayEnrollmentEndComboBox = new javax.swing.JComboBox();
        enrollmentStartCheckBox = new javax.swing.JCheckBox();
        enrollmentEndCheckBox = new javax.swing.JCheckBox();
        monthEnrollmentStartComboBox = new javax.swing.JComboBox();
        startOfClassesCheckBox = new javax.swing.JCheckBox();
        monthStartOfClassesComboBox = new javax.swing.JComboBox();
        dayStartOfClassesComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/disk.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setOpaque(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 30));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ised/resources/images/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setOpaque(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 100, 30));

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("School Year");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, 20));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 10));

        schoolYearTextField.setEditable(false);
        schoolYearTextField.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel5.add(schoolYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText("Status");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        statusComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        statusComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusComboBox.setEnabled(false);
        jPanel5.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 210, -1));

        dayEnrollmentStartComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        dayEnrollmentStartComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dayEnrollmentStartComboBox.setEnabled(false);
        dayEnrollmentStartComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayEnrollmentStartComboBoxItemStateChanged(evt);
            }
        });
        jPanel5.add(dayEnrollmentStartComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, -1));

        monthEnrollmentEndComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        monthEnrollmentEndComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthEnrollmentEndComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monthEnrollmentEndComboBox.setEnabled(false);
        monthEnrollmentEndComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthEnrollmentEndComboBoxItemStateChanged(evt);
            }
        });
        monthEnrollmentEndComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthEnrollmentEndComboBoxActionPerformed(evt);
            }
        });
        jPanel5.add(monthEnrollmentEndComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, -1));

        dayEnrollmentEndComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        dayEnrollmentEndComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dayEnrollmentEndComboBox.setEnabled(false);
        dayEnrollmentEndComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayEnrollmentEndComboBoxItemStateChanged(evt);
            }
        });
        jPanel5.add(dayEnrollmentEndComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 60, -1));

        enrollmentStartCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        enrollmentStartCheckBox.setText("Enrollment Begin");
        enrollmentStartCheckBox.setOpaque(false);
        enrollmentStartCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentStartCheckBoxActionPerformed(evt);
            }
        });
        jPanel5.add(enrollmentStartCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        enrollmentEndCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        enrollmentEndCheckBox.setText("Enrollment End");
        enrollmentEndCheckBox.setOpaque(false);
        enrollmentEndCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentEndCheckBoxActionPerformed(evt);
            }
        });
        jPanel5.add(enrollmentEndCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 117, -1));

        monthEnrollmentStartComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        monthEnrollmentStartComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthEnrollmentStartComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monthEnrollmentStartComboBox.setEnabled(false);
        monthEnrollmentStartComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthEnrollmentStartComboBoxItemStateChanged(evt);
            }
        });
        jPanel5.add(monthEnrollmentStartComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, -1));

        startOfClassesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        startOfClassesCheckBox.setText("Start Of Classes");
        startOfClassesCheckBox.setOpaque(false);
        startOfClassesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startOfClassesCheckBoxActionPerformed(evt);
            }
        });
        jPanel5.add(startOfClassesCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 117, -1));

        monthStartOfClassesComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        monthStartOfClassesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthStartOfClassesComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monthStartOfClassesComboBox.setEnabled(false);
        monthStartOfClassesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthStartOfClassesComboBoxItemStateChanged(evt);
            }
        });
        monthStartOfClassesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthStartOfClassesComboBoxActionPerformed(evt);
            }
        });
        jPanel5.add(monthStartOfClassesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        dayStartOfClassesComboBox.setFont(new java.awt.Font("Tahoma", 1, 12));
        dayStartOfClassesComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dayStartOfClassesComboBox.setEnabled(false);
        dayStartOfClassesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dayStartOfClassesComboBoxItemStateChanged(evt);
            }
        });
        jPanel5.add(dayStartOfClassesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 370, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Date enrollBegin = null;
            Date enrollEnd = null;
            Date startOfClasses = null;

            if (enrollmentStartCheckBox.isSelected()) {
                enrollBegin = ComponentFormatter.formatDate(selectedSchoolYear.getYearFrom(), monthEnrollmentStartComboBox, dayEnrollmentStartComboBox);
            }
            if (enrollmentEndCheckBox.isSelected()) {
                enrollEnd = ComponentFormatter.formatDate(selectedSchoolYear.getYearFrom(), monthEnrollmentEndComboBox, dayEnrollmentEndComboBox);
            }
            if (startOfClassesCheckBox.isSelected()) {
                startOfClasses = ComponentFormatter.formatDate(selectedSchoolYear.getYearFrom(), monthStartOfClassesComboBox, dayStartOfClassesComboBox);
            }

            if (enrollmentStartCheckBox.isSelected() && enrollmentEndCheckBox.isSelected()) {
                if (enrollBegin.getMonth() + 1 > enrollEnd.getMonth() + 1 || (enrollBegin.getMonth() + 1 == enrollEnd.getMonth() + 1 && enrollBegin.getDay() > enrollEnd.getDay())) {
                    JOptionPane.showMessageDialog(parentFrame, "Invalid enrollment period", "WARNING", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            if (startOfClassesCheckBox.isSelected() && enrollmentEndCheckBox.isSelected()) {
                if (startOfClasses.before(enrollEnd)) {
                    JOptionPane.showMessageDialog(parentFrame, "Start of classes must be before the end of enrollment", "WARNING", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }


            if (isAdd) {
                SchoolYear schoolYear = new SchoolYear();
                schoolYear.setYearFrom(selectedSchoolYear.getYearFrom());
                schoolYear.setYearTo(selectedSchoolYear.getYearTo());
                schoolYear.setEnrollmentBegin(enrollBegin);
                schoolYear.setEnrollmentEnd(enrollEnd);
                schoolYear.setStartOfClasses(startOfClasses);
                schoolYear.setSchoolYearStatus(statusComboBox.getSelectedItem().toString());
                schoolYearService.addSchoolYear(schoolYear);
                success = true;
                JOptionPane.showMessageDialog(this, "School Year is successfully added", "Add School Year", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } else {
                selectedSchoolYear.setEnrollmentBegin(enrollBegin);
                selectedSchoolYear.setEnrollmentEnd(enrollEnd);
                selectedSchoolYear.setStartOfClasses(startOfClasses);
                selectedSchoolYear.setSchoolYearStatus(statusComboBox.getSelectedItem().toString());
                schoolYearService.editSchoolYear(selectedSchoolYear);
                success = true;
                JOptionPane.showMessageDialog(this, "School Year is successfully edited", "Edit School Year", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } catch (ExceptionHandler ex) {
            Logger.getLogger(SchoolYearDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void dayEnrollmentStartComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayEnrollmentStartComboBoxItemStateChanged
}//GEN-LAST:event_dayEnrollmentStartComboBoxItemStateChanged

    private void dayEnrollmentEndComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayEnrollmentEndComboBoxItemStateChanged
}//GEN-LAST:event_dayEnrollmentEndComboBoxItemStateChanged

    private void monthEnrollmentEndComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthEnrollmentEndComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthEnrollmentEndComboBoxActionPerformed

    private void enrollmentStartCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentStartCheckBoxActionPerformed
        // TODO add your handling code here:
        if (enrollmentStartCheckBox.isSelected()) {
            updateEnrollmentStartComboBox(true);
        } else {
            updateEnrollmentStartComboBox(false);
        }

    }//GEN-LAST:event_enrollmentStartCheckBoxActionPerformed

    private void enrollmentEndCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentEndCheckBoxActionPerformed
        // TODO add your handling code here:
        if (enrollmentEndCheckBox.isSelected()) {
            updateEnrollmentEndComboBox(true);
        } else {
            updateEnrollmentEndComboBox(false);
        }

    }//GEN-LAST:event_enrollmentEndCheckBoxActionPerformed

    private void startOfClassesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startOfClassesCheckBoxActionPerformed
        // TODO add your handling code here:
        if (startOfClassesCheckBox.isSelected()) {
            updateStartOfClassesComboBox(true);
        } else {
            updateStartOfClassesComboBox(false);
        }
    }//GEN-LAST:event_startOfClassesCheckBoxActionPerformed

    private void monthStartOfClassesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthStartOfClassesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthStartOfClassesComboBoxActionPerformed

    private void dayStartOfClassesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dayStartOfClassesComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dayStartOfClassesComboBoxItemStateChanged

    private void monthEnrollmentStartComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthEnrollmentStartComboBoxItemStateChanged
        // TODO add your handling code here:
        ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthEnrollmentStartComboBox, dayEnrollmentStartComboBox);
    }//GEN-LAST:event_monthEnrollmentStartComboBoxItemStateChanged

    private void monthEnrollmentEndComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthEnrollmentEndComboBoxItemStateChanged
        // TODO add your handling code here:
        ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthEnrollmentEndComboBox, dayEnrollmentEndComboBox);

    }//GEN-LAST:event_monthEnrollmentEndComboBoxItemStateChanged

    private void monthStartOfClassesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthStartOfClassesComboBoxItemStateChanged
        // TODO add your handling code here:
         ComponentFormatter.formatDateComboBox(selectedSchoolYear.getYearFrom(), monthStartOfClassesComboBox, dayStartOfClassesComboBox);
    }//GEN-LAST:event_monthStartOfClassesComboBoxItemStateChanged

    private void updateEnrollmentEndComboBox(boolean flag) {
        monthEnrollmentEndComboBox.setEnabled(flag);
        dayEnrollmentEndComboBox.setEnabled(flag);
    }

    private void updateEnrollmentStartComboBox(boolean flag) {
        monthEnrollmentStartComboBox.setEnabled(flag);
        dayEnrollmentStartComboBox.setEnabled(flag);
    }

    private void updateStartOfClassesComboBox(boolean flag) {
        monthStartOfClassesComboBox.setEnabled(flag);
        dayStartOfClassesComboBox.setEnabled(flag);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox dayEnrollmentEndComboBox;
    private javax.swing.JComboBox dayEnrollmentStartComboBox;
    private javax.swing.JComboBox dayStartOfClassesComboBox;
    private javax.swing.JCheckBox enrollmentEndCheckBox;
    private javax.swing.JCheckBox enrollmentStartCheckBox;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox monthEnrollmentEndComboBox;
    private javax.swing.JComboBox monthEnrollmentStartComboBox;
    private javax.swing.JComboBox monthStartOfClassesComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField schoolYearTextField;
    private javax.swing.JCheckBox startOfClassesCheckBox;
    private javax.swing.JComboBox statusComboBox;
    // End of variables declaration//GEN-END:variables
}
